apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-ylud
  namespace: susdas-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:2ff48c61d54b95682e14dcdedde81dc84ddd923100e9566529888067b5ae16d6
        name: my-python
        resources: {}
status: {}
